---
title: "Multivariate normal"
author: "Dr. Alexander Fisher"
# mainfont: Lato
format: 
  html:
    toc: true
---

## The multivariate normal (MVN)

Motivating examples: 

```{r}
#| echo: false
#| warning: false

library(palmerpenguins)
library(tidyverse)
```


Twenty two students take a reading comprehension test before and after receiving an instructional method. The result for each student is a bivariate vector $Y_i$ that includes a pre- and post- instructional score.

```{r}
#| echo: false
set.seed(123)
s1 = rnorm(22, 75, sd = 5)
s2 = s1 + rnorm(22, 15, sd = 3)
scores = data.frame(s1, s2)

scores %>%
  ggplot(aes(x = s1, y = s2)) + 
  geom_point() +
  theme_bw() +
  labs(x = "score on first test", y = "score on second test", 
       title = "Reading comprehension test scores")
```

```{r}
#| warning: false
#| echo: false
library(plotly)

penguins = penguins %>%
  filter(species == "Gentoo")

bill_length = penguins$bill_length_mm
bill_depth = penguins$bill_depth_mm
body_mass = penguins$body_mass_g

plot_ly(x=bill_length, y=bill_depth, z=body_mass,
        type="scatter3d", mode="markers") %>%
  layout(scene = list(xaxis = list(title = "bill length (mm)"),
                      yaxis = list(title = "bill depth (mm)"),
                      zaxis = list(title = "body mass (g)")))
```

$$
p(y)
$$

